# Generated by Django 5.2.9 on 2026-01-06 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_treatmentrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentrecord',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatment_records', to='core.service'),
        ),
        migrations.AlterField(
            model_name='treatmentrecord',
            name='service_name',
            field=models.CharField(max_length=200),
        ),
    ]
