# Generated by Django 5.2.9 on 2026-01-06 22:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_treatmentrecord_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treatmentrecord',
            name='time',
            field=models.TimeField(default=datetime.time(9, 0)),
            preserve_default=False,
        ),
    ]
