# Generated by Django 5.2.9 on 2026-01-17 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_appointment_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='services',
            field=models.ManyToManyField(blank=True, related_name='professionals', to='core.service'),
        ),
    ]
