# Generated by Django 5.2.9 on 2026-01-18 22:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_professional_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='professional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='core.professional'),
        ),
    ]
