# Generated by Django 5.2.9 on 2026-02-01 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_clientprofile_require_complete_profile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='partner',
            options={'verbose_name': 'Parceria', 'verbose_name_plural': 'Parcerias'},
        ),
        migrations.AlterField(
            model_name='clinicsettings',
            name='clinic_name',
            field=models.CharField(default='FisioUp', max_length=120, verbose_name='Nome da clínica'),
        ),
        migrations.AlterField(
            model_name='clinicsettings',
            name='from_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email de envio'),
        ),
        migrations.AlterField(
            model_name='clinicsettings',
            name='notification_emails',
            field=models.TextField(blank=True, help_text='Emails separados por vírgulas ou por linha. Ex: rececao@..., gerente@...', verbose_name='Emails de notificação'),
        ),
        migrations.AlterField(
            model_name='clinicsettings',
            name='notify_admin_on_pending_registration',
            field=models.BooleanField(default=True, verbose_name='Notificar pedido de registo pendente'),
        ),
        migrations.AlterField(
            model_name='clinicsettings',
            name='notify_client_on_clinic_changes',
            field=models.BooleanField(default=True, verbose_name='Notificar utente quando a clínica altera'),
        ),
        migrations.AlterField(
            model_name='clinicsettings',
            name='notify_clinic_on_client_cancel',
            field=models.BooleanField(default=True, verbose_name='Notificar cancelamento pelo utente'),
        ),
        migrations.AlterField(
            model_name='clinicsettings',
            name='notify_clinic_on_client_reschedule',
            field=models.BooleanField(default=True, verbose_name='Notificar reagendamento pelo utente'),
        ),
        migrations.AlterField(
            model_name='clinicsettings',
            name='notify_clinic_on_new_booking',
            field=models.BooleanField(default=True, verbose_name='Notificar nova marcação'),
        ),
        migrations.AlterField(
            model_name='clinicsettings',
            name='notify_professional_on_new_booking',
            field=models.BooleanField(default=True, verbose_name='Notificar profissional em nova marcação'),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='body_html',
            field=models.TextField(blank=True, verbose_name='Corpo (HTML)'),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='body_text',
            field=models.TextField(blank=True, verbose_name='Corpo (texto)'),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='error',
            field=models.TextField(blank=True, verbose_name='Erro'),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='event',
            field=models.CharField(choices=[('pending_registration', 'Pedido de registo'), ('new_booking', 'Nova marcação'), ('reschedule_client', 'Reagendamento pelo utente'), ('reschedule_clinic', 'Reagendamento pela clínica'), ('cancel_client', 'Cancelamento pelo utente'), ('cancel_clinic', 'Cancelamento pela clínica'), ('password_reset', 'Recuperação de password'), ('generic', 'Genérico')], default='generic', max_length=64, verbose_name='Evento'),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='status',
            field=models.CharField(default='sent', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='subject',
            field=models.CharField(max_length=255, verbose_name='Assunto'),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='to',
            field=models.TextField(verbose_name='Destinatários'),
        ),
    ]
