# Generated by Django 5.2.9 on 2026-02-09 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_group_session_schedule_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clinicsettings',
            name='group_cancel_hours',
            field=models.PositiveIntegerField(default=2, verbose_name='Horas mínimas para cancelamento de turma'),
        ),
    ]
