# Generated by Django 5.2.9 on 2026-02-10 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_alter_clinicsettings_group_cancel_hours'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupenrollment',
            options={'ordering': ('-created_at',), 'verbose_name': 'Inscrição de turma', 'verbose_name_plural': 'Inscrições de turma'},
        ),
        migrations.AlterModelOptions(
            name='groupschedule',
            options={'ordering': ('weekday', 'time'), 'verbose_name': 'Recorrência de turma', 'verbose_name_plural': 'Recorrências de turma'},
        ),
        migrations.AlterModelOptions(
            name='groupsession',
            options={'ordering': ('date', 'time'), 'verbose_name': 'Sessão de turma', 'verbose_name_plural': 'Sessões de turma'},
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Agendada'), ('pending_confirmation', 'Em confirmação'), ('completed', 'Concluída'), ('cancelled', 'Cancelada')], default='scheduled', max_length=20),
        ),
        migrations.AlterField(
            model_name='appointmentlog',
            name='action',
            field=models.CharField(choices=[('created', 'Criada'), ('rescheduled', 'Reagendada'), ('cancelled', 'Cancelada'), ('completed', 'Concluída'), ('notes_updated', 'Notas atualizadas'), ('status_updated', 'Estado atualizado')], max_length=32),
        ),
    ]
