# Generated by Django 5.2.9 on 2026-02-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0049_subcontractor_payments"),
    ]

    operations = [
        migrations.AddField(
            model_name="partnerserviceprice",
            name="discount_type",
            field=models.CharField(
                choices=[("none", "Sem desconto"), ("percent", "Percentagem"), ("fixed", "Valor fixo")],
                default="none",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="partnerserviceprice",
            name="discount_percent",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name="partnerserviceprice",
            name="discount_amount",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
