# Generated by Django 5.2.9 on 2026-02-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0050_partner_service_price_discounts"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinicsettings",
            name="notify_client_on_new_booking",
            field=models.BooleanField(
                default=True,
                verbose_name="Notificar utente quando a clínica cria marcação",
            ),
        ),
    ]
