# Generated by Django 5.2.9 on 2026-02-15 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0051_clinicsettings_notify_client_on_new_booking"),
    ]

    operations = [
        migrations.AddField(
            model_name="clinicsettings",
            name="notify_password_reset",
            field=models.BooleanField(
                default=True,
                verbose_name="Enviar emails de recuperação de password",
            ),
        ),
    ]
