# Generated by Django 5.2.9 on 2026-03-02 12:36

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_appointment_validation_statuses'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMonthlyCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_key', models.CharField(db_index=True, max_length=255)),
                ('class_name', models.CharField(blank=True, default='', max_length=150)),
                ('month', models.DateField(help_text='Primeiro dia do mês de referência.')),
                ('base_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('partner_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('discount_type', models.CharField(choices=[('none', 'Sem desconto'), ('percent', 'Percentagem'), ('fixed', 'Valor fixo')], default='none', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('discount_applied', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('final_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('status', models.CharField(choices=[('unpaid', 'Em dívida'), ('paid', 'Paga'), ('void', 'Anulada')], default='unpaid', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_monthly_charges', to=settings.AUTH_USER_MODEL)),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_monthly_charges', to='core.partner')),
                ('professional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_monthly_charges', to='core.professional')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monthly_charges', to='core.groupschedule')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_monthly_charges', to='core.service')),
            ],
            options={
                'verbose_name': 'Mensalidade de turma',
                'verbose_name_plural': 'Mensalidades de turma',
                'ordering': ('-month', '-id'),
                'unique_together': {('client', 'family_key', 'month')},
            },
        ),
    ]
