# Generated by Django 5.2.9 on 2026-03-02 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_groupmonthlycharge'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('family_key', models.CharField(db_index=True, max_length=255)),
                ('class_name', models.CharField(blank=True, default='', max_length=150)),
                ('weekdays', models.CharField(blank=True, default='', help_text='Dias da semana permitidos (0-6), separados por vírgula.', max_length=32)),
                ('monthly_price_override', models.DecimalField(blank=True, decimal_places=2, help_text='Se definido, substitui o preço mensal base do serviço para este inscrito.', max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to=settings.AUTH_USER_MODEL)),
                ('professional', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_memberships', to='core.professional')),
                ('schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='memberships', to='core.groupschedule')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='core.service')),
            ],
            options={
                'verbose_name': 'Plano de inscrito em turma',
                'verbose_name_plural': 'Planos de inscritos em turma',
                'ordering': ('-updated_at', '-id'),
                'unique_together': {('client', 'family_key')},
            },
        ),
    ]
