# Generated by Django 5.2.9 on 2026-03-02 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_groupmembership'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerserviceprice',
            name='is_enabled',
            field=models.BooleanField(default=True, help_text='Quando desativado, esta parceria não tem efeito neste serviço.'),
        ),
    ]
