# Generated by Django 5.2.9 on 2026-03-23 13:51

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_auditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CashSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('open', 'Aberta'), ('closed', 'Fechada')], db_index=True, default='open', max_length=16)),
                ('opening_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('opening_notes', models.TextField(blank=True, default='')),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('expected_cash_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('counted_cash_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('difference_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('closing_notes', models.TextField(blank=True, default='')),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_sessions_closed', to=settings.AUTH_USER_MODEL)),
                ('opened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_sessions_opened', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sessão de caixa',
                'verbose_name_plural': 'Sessões de caixa',
                'ordering': ('-session_date', '-opened_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='CashMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('in', 'Entrada'), ('out', 'Saída')], db_index=True, max_length=8)),
                ('source_type', models.CharField(choices=[('manual', 'Manual'), ('appointment', 'Marcação')], db_index=True, default='manual', max_length=20)),
                ('payment_method', models.CharField(choices=[('cash', 'Numerário'), ('card', 'Multibanco'), ('mbway', 'MB Way'), ('transfer', 'Transferência'), ('other', 'Outro')], db_index=True, default='cash', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
                ('happened_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_movement', to='core.appointment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_movements_created', to=settings.AUTH_USER_MODEL)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='core.cashsession')),
            ],
            options={
                'verbose_name': 'Movimento de caixa',
                'verbose_name_plural': 'Movimentos de caixa',
                'ordering': ('-happened_at', '-id'),
            },
        ),
    ]
