# Generated by Django 5.2.9 on 2026-03-23 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_cashmovement_is_void_cashmovement_void_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashmovement',
            name='group_monthly_charge',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_movement', to='core.groupmonthlycharge'),
        ),
        migrations.AlterField(
            model_name='cashmovement',
            name='source_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('appointment', 'Marcação'), ('group_monthly', 'Turma')], db_index=True, default='manual', max_length=20),
        ),
    ]
