# Generated by Django 5.2.9 on 2026-03-23 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_cashmovement_group_monthly_charge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashmovement',
            name='client_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_movements', to='core.clientprofile'),
        ),
        migrations.AddField(
            model_name='cashmovement',
            name='stock_movement',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_movement', to='core.stockmovement'),
        ),
        migrations.AlterField(
            model_name='cashmovement',
            name='source_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('appointment', 'Marcação'), ('group_monthly', 'Turma'), ('stock_sale', 'Stock')], db_index=True, default='manual', max_length=20),
        ),
    ]
