# Generated by Django 5.2.9 on 2026-03-24 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_cashmovement_client_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moloniintegration',
            name='company_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='moloniintegration',
            name='company_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
