# Generated by Django 5.2.9 on 2026-03-31 11:20

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0068_moloniintegration_company_id_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="settlement_discount_type",
            field=models.CharField(
                choices=[("none", "Sem desconto"), ("percent", "Percentagem"), ("fixed", "Valor fixo")],
                default="none",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="settlement_discount_value",
            field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=10),
        ),
        migrations.AddField(
            model_name="appointment",
            name="settlement_final_price",
            field=models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=10),
        ),
        migrations.AddField(
            model_name="appointment",
            name="settlement_locked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="appointment",
            name="settlement_notes",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="appointment",
            name="settlement_partner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="appointment_settlements",
                to="core.partner",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="settlement_pricing_mode",
            field=models.CharField(
                choices=[("auto", "Automático"), ("without_partner", "Sem parceria"), ("manual", "Manual")],
                default="auto",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ClientPayment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(choices=[("posted", "Registado"), ("void", "Anulado")], db_index=True, default="posted", max_length=20)),
                ("payment_method", models.CharField(choices=[("cash", "Numerário"), ("card", "Multibanco"), ("mbway", "MB Way"), ("transfer", "Transferência"), ("other", "Outro")], db_index=True, default="cash", max_length=20)),
                ("amount_received", models.DecimalField(decimal_places=2, max_digits=10)),
                ("received_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("reference", models.CharField(blank=True, default="", max_length=255)),
                ("notes", models.TextField(blank=True, default="")),
                ("void_reason", models.CharField(blank=True, default="", max_length=255)),
                ("voided_at", models.DateTimeField(blank=True, null=True)),
                ("moloni_sync_status", models.CharField(choices=[("pending", "Pendente"), ("synced", "Sincronizado"), ("error", "Erro"), ("skipped", "Ignorado")], db_index=True, default="pending", max_length=20)),
                ("moloni_document_id", models.CharField(blank=True, default="", max_length=50)),
                ("moloni_document_number", models.CharField(blank=True, default="", max_length=100)),
                ("moloni_sync_error", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("cash_movement", models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="client_payment", to="core.cashmovement")),
                ("client_profile", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="client_payments", to="core.clientprofile")),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="client_payments_created", to=settings.AUTH_USER_MODEL)),
                ("voided_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="client_payments_voided", to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "verbose_name": "Pagamento de cliente",
                "verbose_name_plural": "Pagamentos de clientes",
                "ordering": ("-received_at", "-id"),
            },
        ),
        migrations.CreateModel(
            name="ClientPaymentAllocation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("allocated_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("notes", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("appointment", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="payment_allocations", to="core.appointment")),
                ("group_monthly_charge", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="payment_allocations", to="core.groupmonthlycharge")),
                ("payment", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="allocations", to="core.clientpayment")),
            ],
            options={
                "verbose_name": "Afetação de pagamento",
                "verbose_name_plural": "Afetações de pagamentos",
                "ordering": ("-created_at", "-id"),
                "unique_together": {("payment", "appointment"), ("payment", "group_monthly_charge")},
            },
        ),
    ]
