# Generated by Django 5.2.9 on 2026-03-31 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0069_appointment_settlement_fields_clientpayment_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cashmovement",
            name="source_type",
            field=models.CharField(
                choices=[
                    ("manual", "Manual"),
                    ("client_payment", "Pagamento de cliente"),
                    ("appointment", "Marcação"),
                    ("group_monthly", "Turma"),
                    ("stock_sale", "Stock"),
                ],
                db_index=True,
                default="manual",
                max_length=20,
            ),
        ),
    ]
