# Generated by Django 5.2.9 on 2026-04-01 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0070_cashmovement_client_payment_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="moloniintegration",
            name="customer_country_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="moloniintegration",
            name="customer_delivery_method_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="moloniintegration",
            name="customer_document_type_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="moloniintegration",
            name="customer_language_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="moloniintegration",
            name="customer_maturity_date_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="moloniintegration",
            name="customer_payment_method_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
