from django.urls import path
from django.contrib.auth import views as auth_views
from .views import (
    home_view, login_view, logout_view, register_view,
    book_view, profile_view,
    my_appointments_view, cancel_appointment_view,
    professional_dashboard_view, professional_calendar_view,
    professional_calendar_events_view,
    reschedule_appointment_view,
    professional_cancel_appointment_view,
    professional_complete_appointment_view,
    professional_customer_detail_view, professional_clients_view,
    professional_book_view, api_professionals_by_service,
    professional_appointment_detail_view,
    professional_customer_form_view,
    professional_profile_view,
    toggle_blocked_slot_view,
    bulk_book_view,
    slots_api_view,
    group_sessions_list_view,
    enroll_group_session_view,
    my_group_sessions_view,
    group_sessions_admin_list_view,
    create_group_sessions_bulk_view,
    group_session_detail_admin_view,
    client_import_view,
    backoffice_dashboard_view,
    backoffice_agenda_view,
    backoffice_clients_quick_view,
    backoffice_services_list_view,
    backoffice_service_create_view,
    backoffice_service_edit_view,
    backoffice_availabilities_list_view,
    backoffice_availability_create_view,
    backoffice_availability_edit_view,
    backoffice_partners_list_view,
    backoffice_partner_create_view,
    backoffice_partner_edit_view,
    backoffice_partner_prices_view,
    backoffice_faturacao_view,
    backoffice_clients_list_view,
    backoffice_client_edit_view,
    backoffice_cancel_appointment_view,
    backoffice_complete_appointment_view,
    backoffice_api_clients_search,
    backoffice_api_professionals_by_service,
    backoffice_api_slots,
    healthcheck_view,
    test_duralux_view,
    PasswordResetRateLimitedView,
    PasswordResetConfirmRateLimitedView,
)
from .forms import EmailPasswordResetForm, ResetPasswordConfirmForm

urlpatterns = [
    path("", home_view, name="home"),
    path("registar/", register_view, name="register"),
    path("login/", login_view, name="login"),
    path("logout/", logout_view, name="logout"),
    path("perfil/", profile_view, name="profile"),

    # PASSWORD RESET
    path(
        "password/reset/",
        PasswordResetRateLimitedView.as_view(
            template_name="registration/password_reset_form.html",
            email_template_name="registration/password_reset_email.html",
            subject_template_name="registration/password_reset_subject.txt",
            form_class=EmailPasswordResetForm,
            success_url="/password/reset/done/",
        ),
        name="password_reset",
    ),
    path(
        "password/reset/done/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="registration/password_reset_done.html",
        ),
        name="password_reset_done",
    ),
    path(
        "password/reset/confirm/<uidb64>/<token>/",
        PasswordResetConfirmRateLimitedView.as_view(
            template_name="registration/password_reset_confirm.html",
            form_class=ResetPasswordConfirmForm,
            success_url="/password/reset/complete/",
        ),
        name="password_reset_confirm",
    ),
    path(
        "password/reset/complete/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="registration/password_reset_complete.html",
        ),
        name="password_reset_complete",
    ),

    # CLIENTE
    path("marcar/", book_view, name="book"),
    path("marcar/serie/", bulk_book_view, name="bulk_book"),
    path("turmas/<int:service_id>/", group_sessions_list_view, name="group_sessions_list"),
    path("turmas/sessao/<int:session_id>/inscrever/", enroll_group_session_view, name="enroll_group_session"),
    path("turmas/minhas/", my_group_sessions_view, name="my_group_sessions"),
    path("minhas-marcacoes/", my_appointments_view, name="my_appointments"),
    path("minhas-marcacoes/<int:appointment_id>/reagendar/", reschedule_appointment_view, name="reschedule_appointment"),
    path("minhas-marcacoes/<int:appointment_id>/cancelar/", cancel_appointment_view, name="cancel_appointment"),

    # PROFISSIONAL
    path("prof/dashboard/", professional_dashboard_view, name="professional_dashboard"),
    path("prof/calendario/", professional_calendar_view, name="professional_calendar"),
    path("prof/calendario/events.json", professional_calendar_events_view, name="professional_calendar_events"),
    path("prof/calendario/bloquear/", toggle_blocked_slot_view, name="toggle_blocked_slot"),
    path("prof/calendario/marcacao/<int:appointment_id>/", professional_appointment_detail_view, name="professional_appointment_detail"),
    path("prof/utentes/", professional_clients_view, name="professional_clients"),
    path("prof/utentes/novo/", professional_customer_form_view, name="prof_customer_create"),
    path("prof/perfil/", professional_profile_view, name="professional_profile"),
    path("prof/marcar/", professional_book_view, name="professional_book"),

    path("prof/calendario/<int:appointment_id>/reagendar/", reschedule_appointment_view, name="professional_reschedule_appointment"),
    path("prof/calendario/<int:appointment_id>/cancelar/", professional_cancel_appointment_view, name="professional_cancel_appointment"),
    path("prof/calendario/<int:appointment_id>/concluir/", professional_complete_appointment_view, name="professional_complete_appointment"),

    path("prof/cliente/<int:client_id>/", professional_customer_detail_view, name="prof_customer_detail"),
    path("prof/cliente/<int:client_id>/editar/", professional_customer_form_view, name="prof_customer_edit"),

    # BACKOFFICE TURMAS
    path("backoffice/turmas/", group_sessions_admin_list_view, name="group_sessions_admin_list"),
    path("backoffice/turmas/criar-em-massa/", create_group_sessions_bulk_view, name="group_sessions_bulk_create"),
    path("backoffice/turmas/<int:session_id>/", group_session_detail_admin_view, name="group_session_detail_admin"),
    path("backoffice/importar-clientes/", client_import_view, name="client_import"),
    path("backoffice/", backoffice_dashboard_view, name="backoffice_dashboard"),
    path("backoffice/agenda/", backoffice_agenda_view, name="backoffice_agenda"),
    path("backoffice/agenda/<int:appointment_id>/cancelar/", backoffice_cancel_appointment_view, name="backoffice_cancel_appointment"),
    path("backoffice/agenda/<int:appointment_id>/concluir/", backoffice_complete_appointment_view, name="backoffice_complete_appointment"),
    path("backoffice/utentes/", backoffice_clients_quick_view, name="backoffice_clients_quick"),
    path("backoffice/servicos/", backoffice_services_list_view, name="backoffice_services"),
    path("backoffice/servicos/novo/", backoffice_service_create_view, name="backoffice_service_new"),
    path("backoffice/servicos/<int:service_id>/editar/", backoffice_service_edit_view, name="backoffice_service_edit"),
    path("backoffice/disponibilidades/", backoffice_availabilities_list_view, name="backoffice_availabilities"),
    path("backoffice/disponibilidades/nova/", backoffice_availability_create_view, name="backoffice_availability_new"),
    path("backoffice/disponibilidades/<int:availability_id>/editar/", backoffice_availability_edit_view, name="backoffice_availability_edit"),
    path("backoffice/parcerias/", backoffice_partners_list_view, name="backoffice_partners"),
    path("backoffice/parcerias/novo/", backoffice_partner_create_view, name="backoffice_partner_new"),
    path("backoffice/parcerias/<int:partner_id>/editar/", backoffice_partner_edit_view, name="backoffice_partner_edit"),
    path("backoffice/precos/", backoffice_partner_prices_view, name="backoffice_partner_prices"),
    path("backoffice/faturacao/", backoffice_faturacao_view, name="backoffice_faturacao"),
    path("backoffice/clientes/", backoffice_clients_list_view, name="backoffice_clients"),
    path("backoffice/clientes/<int:client_id>/editar/", backoffice_client_edit_view, name="backoffice_client_edit"),
    path("backoffice/api/clients/search/", backoffice_api_clients_search, name="backoffice_api_clients_search"),
    path("backoffice/api/professionals/by-service/", backoffice_api_professionals_by_service, name="backoffice_api_professionals_by_service"),
    path("backoffice/api/slots/", backoffice_api_slots, name="backoffice_api_slots"),

    path("api/profissionais/", api_professionals_by_service, name="api_professionals_by_service"),
    path("api/slots/", slots_api_view, name="slots_api"),
    path("test-duralux/", test_duralux_view, name="test_duralux"),
    path("health/", healthcheck_view, name="healthcheck"),
]
