from django.urls import path
from django.contrib.auth import views as auth_views
import core.views as views
from .forms import EmailPasswordResetForm, ResetPasswordConfirmForm

urlpatterns = [
    path("", views.home_view, name="home"),
    path("registar/", views.register_view, name="register"),
    path("login/", views.login_view, name="login"),
    path("logout/", views.logout_view, name="logout"),
    path("session/keepalive/", views.session_keepalive_view, name="session_keepalive"),
    path("perfil/", views.profile_view, name="profile"),
    path("privacidade/", views.privacy_view, name="privacy"),
    path("termos/", views.terms_view, name="terms"),
    path("cookies/", views.cookies_view, name="cookies"),
    path("ajuda/", views.help_view, name="help"),

    # PASSWORD RESET
    path(
        "password/reset/",
        views.PasswordResetRateLimitedView.as_view(
            template_name="registration/password_reset_form.html",
            email_template_name="registration/password_reset_email.html",
            subject_template_name="registration/password_reset_subject.txt",
            form_class=EmailPasswordResetForm,
            success_url="/password/reset/done/",
        ),
        name="password_reset",
    ),
    path(
        "password/reset/done/",
        auth_views.PasswordResetDoneView.as_view(
            template_name="registration/password_reset_done.html",
        ),
        name="password_reset_done",
    ),
    path(
        "password/reset/confirm/<uidb64>/<token>/",
        views.PasswordResetConfirmRateLimitedView.as_view(
            template_name="registration/password_reset_confirm.html",
            form_class=ResetPasswordConfirmForm,
            success_url="/password/reset/complete/",
        ),
        name="password_reset_confirm",
    ),
    path(
        "password/reset/complete/",
        auth_views.PasswordResetCompleteView.as_view(
            template_name="registration/password_reset_complete.html",
        ),
        name="password_reset_complete",
    ),

    # CLIENTE
    path("marcar/", views.book_view, name="book"),
    path("marcar/serie/", views.book_view, name="bulk_book"),
    path("turmas/", views.group_services_list_view, name="group_services_list"),
    path("turmas/<int:service_id>/", views.group_sessions_list_view, name="group_sessions_list"),
    path("turmas/sessao/<int:session_id>/inscrever/", views.enroll_group_session_view, name="enroll_group_session"),
    path("turmas/sessao/<int:session_id>/cancelar/", views.cancel_group_session_enrollment_view, name="cancel_group_session_enrollment"),
    path("turmas/minhas/", views.my_group_sessions_view, name="my_group_sessions"),
    path("minhas-marcacoes/", views.my_appointments_view, name="my_appointments"),
    path("minhas-marcacoes/<int:appointment_id>/reagendar/", views.reschedule_appointment_view, name="reschedule_appointment"),
    path("minhas-marcacoes/<int:appointment_id>/cancelar/", views.cancel_appointment_view, name="cancel_appointment"),
    path("calendario/", views.client_calendar_fullcalendar_test_view, name="client_calendar"),
    path("calendario/events.json", views.client_calendar_events_view, name="client_calendar_events"),
    path("calendario/availabilities.json", views.client_calendar_availability_events_view, name="client_calendar_availability_events"),
    path("calendario/quick-create/", views.client_calendar_quick_create_view, name="client_calendar_quick_create"),
    path("calendario/availability-options/", views.client_calendar_availability_options_view, name="client_calendar_availability_options"),

    # PROFISSIONAL
    path("prof/dashboard/", views.professional_dashboard_view, name="professional_dashboard"),
    path("prof/marcacoes/", views.backoffice_agenda_view, name="professional_agenda"),
    path("prof/notificacoes/", views.professional_notifications_view, name="professional_notifications"),
    path("prof/calendario/", views.professional_calendar_fullcalendar_test_view, name="professional_calendar"),
    path("prof/calendario/events.json", views.professional_calendar_events_view, name="professional_calendar_events"),
    path("prof/calendario/availabilities.json", views.professional_calendar_availability_events_view, name="professional_calendar_availability_events"),
    path("prof/api/clients/search/", views.professional_clients_search_view, name="professional_clients_search"),
    path("prof/calendario/quick-create/", views.professional_calendar_quick_create_view, name="professional_calendar_quick_create"),
    path("prof/calendario/reschedule-context/", views.professional_reschedule_context_view, name="professional_reschedule_context"),
    path("prof/calendario/availability-options/", views.professional_calendar_availability_options_view, name="professional_calendar_availability_options"),
    path("prof/calendario/bloquear/", views.toggle_blocked_slot_view, name="toggle_blocked_slot"),
    path("prof/calendario/marcacao/<int:appointment_id>/", views.professional_appointment_detail_view, name="professional_appointment_detail"),
    path("prof/calendario/marcacao/<int:appointment_id>/confirmar/", views.professional_confirm_appointment_view, name="professional_confirm_appointment"),
    path("notifications/mark-read/", views.mark_notifications_read_view, name="mark_notifications_read"),
    path("prof/utentes/", views.professional_clients_view, name="professional_clients"),
    path("prof/utentes/novo/", views.professional_customer_form_view, name="prof_customer_create"),
    path("prof/perfil/", views.professional_profile_view, name="professional_profile"),
    path("prof/marcar/", views.professional_book_view, name="professional_book"),

    path("prof/calendario/<int:appointment_id>/reagendar/", views.reschedule_appointment_view, name="professional_reschedule_appointment"),
    path("prof/calendario/<int:appointment_id>/cancelar/", views.professional_cancel_appointment_view, name="professional_cancel_appointment"),
    path("prof/calendario/<int:appointment_id>/concluir/", views.professional_complete_appointment_view, name="professional_complete_appointment"),
    path("prof/turmas/", views.professional_group_sessions_view, name="professional_group_sessions"),
    path("prof/turmas/<int:session_id>/", views.professional_group_session_detail_view, name="professional_group_session_detail"),

    path("prof/cliente/<int:client_id>/", views.professional_customer_detail_view, name="prof_customer_detail"),
    path("prof/cliente/<int:client_id>/editar/", views.professional_customer_form_view, name="prof_customer_edit"),
    path("prof/cliente/<int:client_id>/apagar/", views.professional_customer_delete_view, name="prof_customer_delete"),

    # BACKOFFICE TURMAS
    path("backoffice/turmas/", views.group_sessions_admin_list_view, name="group_sessions_admin_list"),
    path("backoffice/turmas/novo/", views.group_session_create_view, name="group_session_create"),
    path("backoffice/turmas/<int:schedule_id>/editar/", views.group_schedule_edit_view, name="group_schedule_edit"),
    path("backoffice/turmas/<int:session_id>/", views.group_session_detail_admin_view, name="group_session_detail_admin"),
    path("backoffice/importar-clientes/", views.client_import_view, name="client_import"),
    path("backoffice/", views.backoffice_dashboard_view, name="backoffice_dashboard"),
    path("backoffice/stock/", views.backoffice_stock_dashboard_view, name="backoffice_stock_dashboard"),
    path("backoffice/stock/produtos/", views.backoffice_stock_products_list_view, name="backoffice_stock_products"),
    path("backoffice/stock/produtos/novo/", views.backoffice_stock_product_create_view, name="backoffice_stock_product_new"),
    path("backoffice/stock/produtos/<int:product_id>/editar/", views.backoffice_stock_product_edit_view, name="backoffice_stock_product_edit"),
    path("backoffice/stock/categorias/", views.backoffice_stock_categories_list_view, name="backoffice_stock_categories"),
    path("backoffice/stock/categorias/novo/", views.backoffice_stock_category_create_view, name="backoffice_stock_category_new"),
    path("backoffice/stock/categorias/<int:category_id>/editar/", views.backoffice_stock_category_edit_view, name="backoffice_stock_category_edit"),
    path("backoffice/stock/entradas/", views.backoffice_stock_entries_view, name="backoffice_stock_entries"),
    path("backoffice/stock/ajustes/", views.backoffice_stock_adjustments_view, name="backoffice_stock_adjustments"),
    path("backoffice/stock/movimentos/", views.backoffice_stock_movements_view, name="backoffice_stock_movements"),
    path("backoffice/agenda/", views.backoffice_agenda_view, name="backoffice_agenda"),
    path("backoffice/caixa/", views.backoffice_cash_dashboard_view, name="backoffice_cash_dashboard"),
    path("backoffice/caixa/<int:session_id>/imprimir/", views.backoffice_cash_session_print_view, name="backoffice_cash_session_print"),
    path("backoffice/agenda/<int:appointment_id>/cancelar/", views.backoffice_cancel_appointment_view, name="backoffice_cancel_appointment"),
    path("backoffice/agenda/<int:appointment_id>/concluir/", views.backoffice_complete_appointment_view, name="backoffice_complete_appointment"),
    path("backoffice/utentes/", views.backoffice_clients_quick_view, name="backoffice_clients_quick"),
    path("backoffice/servicos/", views.backoffice_services_list_view, name="backoffice_services"),
    path("backoffice/servicos/novo/", views.backoffice_service_create_view, name="backoffice_service_new"),
    path("backoffice/servicos/<int:service_id>/editar/", views.backoffice_service_edit_view, name="backoffice_service_edit"),
    path("backoffice/profissionais/", views.backoffice_professionals_list_view, name="backoffice_professionals"),
    path("backoffice/profissionais/novo/", views.backoffice_professional_create_view, name="backoffice_professional_new"),
    path("backoffice/profissionais/<int:professional_id>/editar/", views.backoffice_professional_edit_view, name="backoffice_professional_edit"),
    path("backoffice/horarios/", views.backoffice_weekly_schedules_list_view, name="backoffice_weekly_schedules"),
    path("backoffice/horarios/<int:professional_id>/editar/", views.backoffice_weekly_schedule_edit_view, name="backoffice_weekly_schedule_edit"),
    path("backoffice/parcerias/", views.backoffice_partners_list_view, name="backoffice_partners"),
    path("backoffice/parcerias/novo/", views.backoffice_partner_create_view, name="backoffice_partner_new"),
    path("backoffice/parcerias/<int:partner_id>/editar/", views.backoffice_partner_edit_view, name="backoffice_partner_edit"),
    path("backoffice/precos/", views.backoffice_partner_prices_view, name="backoffice_partner_prices"),
    path("backoffice/settings/email/", views.backoffice_settings_email_view, name="backoffice_settings_email"),
    path("backoffice/settings/moloni/", views.backoffice_settings_moloni_view, name="backoffice_settings_moloni"),
    path("backoffice/settings/moloni/connect/", views.backoffice_moloni_connect_view, name="backoffice_moloni_connect"),
    path("backoffice/settings/moloni/callback/", views.backoffice_moloni_callback_view, name="backoffice_moloni_callback"),
    path("backoffice/settings/moloni/select-company/", views.backoffice_moloni_select_company_view, name="backoffice_moloni_select_company"),
    path("backoffice/settings/moloni/test/", views.backoffice_moloni_test_view, name="backoffice_moloni_test"),
    path("backoffice/settings/moloni/sync-customers/", views.backoffice_moloni_sync_customers_view, name="backoffice_moloni_sync_customers"),
    path("backoffice/settings/moloni/disconnect/", views.backoffice_moloni_disconnect_view, name="backoffice_moloni_disconnect"),
    path("backoffice/settings/auditoria/", views.backoffice_audit_logs_view, name="backoffice_audit_logs"),
    path("backoffice/settings/auditoria/<int:log_id>/", views.backoffice_audit_log_detail_view, name="backoffice_audit_log_detail"),
    path("backoffice/settings/criador-posts/", views.backoffice_post_designer_view, name="backoffice_post_designer"),
    path("backoffice/settings/criador-posts/criar-destaque/", views.backoffice_post_designer_create_highlight_view, name="backoffice_post_designer_create_highlight"),
    path("backoffice/settings/destaques/", views.backoffice_highlights_list_view, name="backoffice_highlights"),
    path("backoffice/settings/destaques/novo/", views.backoffice_highlight_create_view, name="backoffice_highlight_new"),
    path("backoffice/settings/destaques/<int:post_id>/editar/", views.backoffice_highlight_edit_view, name="backoffice_highlight_edit"),
    path("backoffice/faturacao/", views.backoffice_faturacao_view, name="backoffice_faturacao"),
    path("backoffice/subcontratados/", views.backoffice_subcontractors_view, name="backoffice_subcontractors"),
    path("backoffice/subcontratados/exportar/", views.backoffice_subcontractors_export_view, name="backoffice_subcontractors_export"),
    path("backoffice/clientes/", views.backoffice_clients_list_view, name="backoffice_clients"),
    path("backoffice/clientes/<int:client_id>/editar/", views.backoffice_client_edit_view, name="backoffice_client_edit"),
    path("backoffice/api/clients/search/", views.backoffice_api_clients_search, name="backoffice_api_clients_search"),
    path("backoffice/api/professionals/by-service/", views.backoffice_api_professionals_by_service, name="backoffice_api_professionals_by_service"),
    path("backoffice/api/slots/", views.backoffice_api_slots, name="backoffice_api_slots"),

    path("api/profissionais/", views.api_professionals_by_service, name="api_professionals_by_service"),
    path("api/slots/", views.slots_api_view, name="slots_api"),
    path("test-duralux/", views.test_duralux_view, name="test_duralux"),
    path("teste-fullcalendar/", views.test_fullcalendar, name="test_fullcalendar"),
    path("health/", views.healthcheck_view, name="healthcheck"),
]
